modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory (24 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="overpowered_pickles" #mandatory
version="1.1.2" #mandatory
displayName="OverpoweredPickles" #mandatory
description='''
A collection of overpowered pickles
'''


[[dependencies.overpowered_pickles]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.overpowered_pickles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
